# Generated by Django 4.0 on 2022-03-24 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
